version: '3.8'
services:
  # FastAPI App
  web:
    env_file:
      - .env
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - redis
    container_name: fastapi

  # Celery worker
  worker:
    env_file:
      - .env
    build: .
    command: celery -A src.worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - beat
    container_name: fastapi_celery_app

# Celery beats
  beat:
    env_file:
      - .env
    build: .
    command: celery -A src.worker.celery beat -S redbeat.RedBeatScheduler --max-interval 30  --loglevel=debug
    volumes:
      - .:/app

    depends_on:
      - web
      - redis

    container_name: fastapi_celery_beats

  # Redis DB
  redis:
    image: redis:7
    container_name: redis_db
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis_data: