version: '3.8'
services:
  # FastAPI App
  web:
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - ATLAS_SEARCH_INDEX_NAME=${ATLAS_SEARCH_INDEX_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - BUCKET_BASE_URL=${BUCKET_BASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EVENT_CHECK_INTERVAL_MINUTES=1
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - redis
    container_name: fastapi

  # Celery worker
  worker:
    environment:
      - EVENT_CHECK_INTERVAL_MINUTES=1
      - MONGODB_URL=${MONGODB_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build: .
    command: celery -A src.worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - beat
    container_name: fastapi_celery_app

# Celery beats
  beat:
    environment:
      - EVENT_CHECK_INTERVAL_MINUTES=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build: .
    command: celery -A src.worker.celery beat -S redbeat.RedBeatScheduler --max-interval 30  --loglevel=debug
    volumes:
      - .:/app

    depends_on:
      - web
      - redis

    container_name: fastapi_celery_beats

  # Redis DB
  redis:
    image: redis:7
    container_name: redis_db
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis_data: